const pickupliness = [
    `the first time i saw you i said MASHALLAH and ever since i've been saying INSHALLAH.`,
    `Are you the solution to the equation x^2-2x+1=0? Because i just used the quadratic formula and you’re the 1`,
    `roses are red, lemons are sour, Spread you legs and give me an hour.`,
    `are you a pickaxe? cause i wanna make you mine.`,
    `Hey baby did you sit on the f5 key ? Cause that ass is refreshing.`,
    `when god made you, He was showing off his skills.`,
    `Please tell me you know CPR, cause you're taking my breath away.`,
    `Are you siri? Because you auto complete me.`,
    `Hey are you corona? because you take my breath away.`,
    `i'm in the mood for pizza, A pizza you, that is!`,
    `How do you pronounce you last name? Doesn't matter... i'm gonna change it anyways`,
    `Hey, I know you're short, but you still somehow managed to touch my heart.`,
    `Hey girl are you a rope? cuz i wanna hang out with you.`,
    `Are you a batch of cookies In the oven?, Because i can't wait to take you out.`,
    `I would say may God bless you, but it looks like he already did.`,
    `Damn girl are you asthma?, Cause you're breathtaking`,
    `Hey girl what's you frequency? Cuz i wanna resonate with you.`,
    `Are you French? Because Eiffel for you.`,
    `Are you from Tennessee? Because you're the only 10 i see!`,
    `i'm no photographer, But i can Picture us together`,
    `Are a you a bank loan? cuz you got my interest`,
    `Hey cutie are you into Pokemon?, cuz just a peek-at-chu make me wanna squirt-a-lil`,
    `Forget about Superman or Ironman, All i wanna be is your man`,
    `Are you a magician? cuz whenever i look at you, everyone else disappears!`,
    `is there an airport nearby or is it my heart taking off?`,
    `was you dad a boxer ? cuz damn, you're a knockout!`,
    `Aside from being sexy, what do you do for a living?`,
    `if you were a triangle, you'd be acute one!`,
    `out all your curves, your smile is my favourite.`
]


const puns = [
    `Light travels faster than sound. That's why some people appear bright until you hear them speak`,
    `I was wondering why the ball was getting bigger. Then it hit me`,
    `I have a few jokes about unemployed people, but none of them work`,
    `How do you make holy water ? You boil the hell out of it.`,
    `I Renamed my iPod The Titanic, so when I plug it in, it says "The Titanic is syncing."`,
    `Last night, I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta sea`,
    `Will glass coffins be a success? Remains to be seen`,
    `It's hard to explain puns to kleptomaniacs because they always take things literally`,
    `Two windmills are standing in a wind farm. One asks, “What’s your favorite kind of music?” The other says, "I’m a big metal fan."`,
    `I can’t believe I got fired from the calendar factory. All I did was take a day off`,
    `The man who survived pepper spray and mustard gas is now a seasoned veteran`,
    `My dad farted in an elevator, it was wrong on so many levels`,
    `I went to buy some camouflage trousers yesterday but couldn't find any`,
    `England doesn't have a kidney bank, but it does have a Liverpool`,
    `I tried to sue the airline for losing my luggage. I lost my case`,
    `Jill broke her finger today, but on the other hand she was completely fine`,
    `A cross-eyed teacher couldn’t control his pupils`,
    `When the past, present, and future go camping they always argue. It's intense tense in tents`,
    `Is it ignorance or apathy that's destroying the world today? I don't know and don't really care`,
    `A mean crook going down stairs = A condescending con, descending`,
    `I wasn’t originally going to get a brain transplant, but then I changed my mind`,
    `Which country’s capital has the fastest-growing population? Ireland. Every day it’s Dublin.`,
    `What do you call the wife of a hippie? A Mississippi`,
    `What washes up on tiny beaches? Microwaves`,
    `How does an attorney sleep? First he lies on one side, then he lies on the other`,
    `My ex-wife still misses me. But her aim is starting to improve`,
    `What are the strongest days of the week? Saturday and Sunday, the rest are weekdays`,
    `Two fish are in a tank, one says to the other "how do you drive this thing?"`,
    `The other day I tried to make a chemistry joke, but got no reaction`,
    `Need an ark? I Noah guy`,
    `Sleeping comes so naturally to me, I could do it with my eyes closed`,
    `it doesn't matter how kind you are. German children are always kinder`,
    `I used to be indecisive; now I'm not so sure`,
    `I walked into my sister's room and tripped on a bra... It was a booby trap`,
    `I like European food so I decided to Russia over there because I was Hungary. After Czech'ing the menu I ordered Turkey. When I was Finnished I told the waiter 'Spain good but there is Norway I could eat another bite'`,
    `Why are frogs so happy? They eat whatever bugs them`,
    `The machine at the coin factory just suddenly stopped working, with no explanation. It doesn’t make any cents`,
    `What did the grape say when it got stepped on? Nothing - but it let out a little whine`,
    `What do you call a super articulate dinosaur? A Thesaurus`,
    `I bought a boat because it was for sail`,
    `What did one flag say to the other? Nothing, it just waved.`,
    `I lost my mood ring, and I don't know how I'm feeling about that`,
    `How was Rome split in two? With a pair of Ceasars`
]

module.exports = {
    pickuplines: pickupliness,
    puns: puns
};
